//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.QuoteDownloadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuoteDownloadService.IQuoteDownloadService")]
    public interface IQuoteDownloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteDownloadService/Echo", ReplyAction="http://tempuri.org/IQuoteDownloadService/EchoResponse")]
        string Echo(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteDownloadService/Echo", ReplyAction="http://tempuri.org/IQuoteDownloadService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteDownloadService/FilterCompanies", ReplyAction="http://tempuri.org/IQuoteDownloadService/FilterCompaniesResponse")]
        string[] FilterCompanies(string[] tickers, System.Nullable<decimal> percentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteDownloadService/FilterCompanies", ReplyAction="http://tempuri.org/IQuoteDownloadService/FilterCompaniesResponse")]
        System.Threading.Tasks.Task<string[]> FilterCompaniesAsync(string[] tickers, System.Nullable<decimal> percentage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuoteDownloadServiceChannel : WebUI.QuoteDownloadService.IQuoteDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuoteDownloadServiceClient : System.ServiceModel.ClientBase<WebUI.QuoteDownloadService.IQuoteDownloadService>, WebUI.QuoteDownloadService.IQuoteDownloadService {
        
        public QuoteDownloadServiceClient() {
        }
        
        public QuoteDownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuoteDownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteDownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteDownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string message) {
            return base.Channel.Echo(message);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string message) {
            return base.Channel.EchoAsync(message);
        }
        
        public string[] FilterCompanies(string[] tickers, System.Nullable<decimal> percentage) {
            return base.Channel.FilterCompanies(tickers, percentage);
        }
        
        public System.Threading.Tasks.Task<string[]> FilterCompaniesAsync(string[] tickers, System.Nullable<decimal> percentage) {
            return base.Channel.FilterCompaniesAsync(tickers, percentage);
        }
    }
}
